services:
  websocket_gateway:
    image: python:3.9-slim
    container_name: websocket_gateway
    working_dir: /app
    restart: always  # Перезапуск при сбое
    volumes:
      - ./:/app
    ports:
      - "4000:4000"  # FastAPI HTTPS
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt 
      && python3 -m app.main"
